### PR TITLE
add option to configure the request payload size

### PR DESCRIPTION
**Pull request by gVolop**

### CODE REVIEW

**Comment by madnight** [comment]
thx!
the default limit is 100kb, so a variable payload length for larger pdfs would make sense indeed
i'll test that

**Comment by gVolop** [comment]
👍 tks :)
.. meanwhile i built an image from my fork

**Comment by madnight** [comment]
i added a branch that contains your commit + rebase + some changes + tests
https://github.com/Traum-Ferienwohnungen/docker-wkhtmltopdf-aas/compare/master...Traum-Ferienwohnungen:payload-size
the test asserts that big pdf file generating is working, the test fails without increased payload limit option

**Comment by madnight** [comment]
merged

**Pull request closed without merging**
